FROM node:16-alpine3.12

LABEL version="1.0"
LABEL description="React Frontend for the Real ESTATE API"

WORKDIR /app

COPY ./package*.json ./

RUN npm install

COPY . . /app/

CMD ["npm", "run", "start"]